{
 "title": "Big Data Visualization 1 Copy: year",
 "time": { "from": "1999-12-31T21:00:00.000Z", "to": "2023-01-02T21:02:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Select Country",
    "query": "SELECT DISTINCT country FROM affiliation"
   },
   {
    "name": "city",
    "label": "Select City",
    "query": "SELECT DISTINCT city FROM affiliation WHERE country = '$country' or country = 'All' "
   },
   {
    "name": "university",
    "label": "Select University",
    "query": "SELECT DISTINCT name FROM affiliation WHERE city = '$city' or city= 'All' "
   },
   {
    "name": "subject",
    "label": "Select Subject",
    "query": "SELECT DISTINCT short_name FROM subject"
   },
   {
    "name": "year",
    "label": "Year",
    "query": "All, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022"
   }
  ]
 },
 "panels": [
  {
   "title": "top stran",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  current_date AS Time,\r\n  a.country AS Country,\r\n  count(*) AS Count\r\nFROM \r\n  publication_author pa\r\nINNER JOIN \r\n  publication p\r\n  ON p.id = pa.publication_id\r\nINNER JOIN \r\n  affiliation a\r\n\tON a.id = pa.affiliation_id\r\nINNER JOIN publication_subject ps\r\n\tON p.id = ps.publication_id\r\nINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\n  WHERE\r\n  ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n\t  and ('$year'= 'All' and date_part('year', p.cover_date::timestamp)::text <> '' or '$year' <> 'All' and date_part('year'::text, p.cover_date::timestamp)::text = '$year')\r\nGROUP BY \r\n  a.country"
    }
   ]
  },
  {
   "title": "Статистика среднего размера публикаций по годам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(s.year),\r\n  s.avg_size\r\nFROM (\r\n  SELECT date_trunc('year', p.cover_date::timestamp) AS \"year\",\r\n         avg((NULLIF(substring(substring(page_range from POSITION('-' IN page_range) + 1) from '^(\\d+)(\\D.*)?$'), '')::numeric -\r\n\t\t\t   NULLIF(substring(page_range from '^(\\d+)(-.*)?$'), '')::numeric)) AS \"avg_size\"\r\n  FROM publication p\r\n  INNER JOIN \r\n    publication_author pa\r\n    ON p.id = pa.publication_id\r\n  INNER JOIN \r\n    affiliation a\r\n  \tON a.id = pa.affiliation_id\r\n  INNER JOIN publication_subject ps\r\n  \tON p.id = ps.publication_id\r\n  INNER JOIN subject su\r\n  \tON su.id = ps.subject_id\r\n  WHERE\r\n  \t(a.country = '$country' or '$country' = 'All') and ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n      and (a.city = '$city' or '$city' = 'All') and (a.name = '$university' or '$university' = 'All')\r\n  GROUP BY date_trunc('year', p.cover_date::timestamp)\r\n  ORDER BY date_trunc('year', p.cover_date::timestamp)\r\n) s\r\nWHERE\r\n  $__timeFilter(s.year)"
    }
   ]
  },
  {
   "title": "Cтатистика популярности месяцев по количеству публикаций",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(current_date),\r\n  date_part('month', p.cover_date::timestamp) AS \"month\",\r\n  count(*) AS \"amount\"\r\nFROM\r\n  publication p\r\nINNER JOIN \r\n  publication_author pa\r\n  ON p.id = pa.publication_id\r\nINNER JOIN \r\n  affiliation a\r\n\tON a.id = pa.affiliation_id\r\nINNER JOIN publication_subject ps\r\n\tON p.id = ps.publication_id\r\nINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\nWHERE\r\n\t(a.country = '$country' or '$country' = 'All') and ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n    and (a.city = '$city' or '$city' = 'All') and (a.name = '$university' or '$university' = 'All')\r\n      and ('$year'= 'All' and date_part('year', p.cover_date::timestamp)::text <> '' or '$year' <> 'All' and date_part('year'::text, p.cover_date::timestamp)::text = '$year')\r\nGROUP BY\r\n  date_part('month', p.cover_date::timestamp)\r\nORDER BY\r\n  date_part('month', p.cover_date::timestamp)"
    }
   ]
  },
  {
   "title": "Статистика популярности областей по количеству публикаций",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(current_date),\r\n  s.short_name AS \"subject\",\r\n  count(*) AS \" \"\r\nFROM\r\n  publication_subject ps\r\nINNER JOIN publication p\r\n  ON ps.publication_id = p.id\r\nINNER JOIN subject s\r\n  ON ps.subject_id = s.id\r\nINNER JOIN \r\n  publication_author pa\r\n  ON p.id = pa.publication_id\r\nINNER JOIN \r\n  affiliation a\r\n\tON a.id = pa.affiliation_id\r\nWHERE\r\n\t(a.country = '$country' or '$country' = 'All')\r\n    and (a.city = '$city' or '$city' = 'All') and (a.name = '$university' or '$university' = 'All')\r\n      and ('$year'= 'All' and date_part('year', p.cover_date::timestamp)::text <> '' or '$year' <> 'All' and date_part('year'::text, p.cover_date::timestamp)::text = '$year')\r\nGROUP BY\r\n  s.short_name\r\nORDER BY\r\n  s.short_name"
    }
   ]
  },
  {
   "title": "Cтатистика количества публикаций по типу документов категории Open Access",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(current_date),\r\n  fl.name AS metric,\r\n  count(*) AS value\r\nFROM\r\n  publication_freetoread_label pfl\r\nINNER JOIN freetoread_label fl\r\n  ON pfl.freetoread_label_id = fl.id\r\nWHERE\r\n  $__timeFilter(current_date)\r\nGROUP BY\r\n  fl.name"
    }
   ]
  },
  {
   "title": "Cтатистика количества публикаций в зависимости от нахождения публикации в открытом доступе",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(current_date),\r\n  count(pfl.*) AS \"OpenAccess\",\r\n  (count(p.*) - count(pfl.*)) AS \"CloseAccess\"\r\nFROM\r\n  publication_freetoread_label pfl\r\nFULL JOIN publication p\r\n  ON pfl.publication_id = p.id\r\nWHERE\r\n  $__timeFilter(current_date)"
    }
   ]
  },
  {
   "title": "Анализ изменения популярности университетов/городов/стран",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__time(s.year),\r\n  s.amount AS \"Country\"\r\nFROM (\r\n  SELECT date_trunc('year', p.cover_date::timestamp) AS \"year\",\r\n         count(*) AS \"amount\"\r\n  FROM publication_author pa\r\n  INNER JOIN publication p\r\n\tON p.id = pa.publication_id\r\n  INNER JOIN affiliation a\r\n\tON a.id = pa.affiliation_id\r\n\tINNER JOIN publication_subject ps\r\n\tON p.id = ps.publication_id\r\n\tINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\n  WHERE\r\n\t(a.country = '$country' or '$country' = 'All') and ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n  GROUP BY date_trunc('year', p.cover_date::timestamp)\r\n  ORDER BY date_trunc('year', p.cover_date::timestamp)\r\n) s\r\nWHERE\r\n  $__timeFilter(s.year)"
    },
    {
     "rawSql": "SELECT\r\n  $__time(s.year),\r\n  s.amount AS \"City\"\r\nFROM (\r\n  SELECT date_trunc('year', p.cover_date::timestamp) AS \"year\",\r\n         count(*) AS \"amount\"\r\n  FROM publication_author pa\r\n  INNER JOIN publication p\r\n\tON p.id = pa.publication_id\r\n  INNER JOIN affiliation a\r\n\tON a.id = pa.affiliation_id\r\n\tINNER JOIN publication_subject ps\r\n\tON p.id = ps.publication_id\r\n\tINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\n  WHERE\r\n  (a.country = '$country' or '$country' = 'All') and ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n\t  and (a.city = '$city' or '$city' = 'All')\r\n  GROUP BY date_trunc('year', p.cover_date::timestamp)\r\n  ORDER BY date_trunc('year', p.cover_date::timestamp)\r\n) s\r\nWHERE\r\n  $__timeFilter(s.year)"
    },
    {
     "rawSql": "SELECT\r\n  $__time(s.year),\r\n  s.amount AS \"University\"\r\nFROM (\r\n  SELECT date_trunc('year', p.cover_date::timestamp) AS \"year\",\r\n         count(*) AS \"amount\"\r\n  FROM publication_author pa\r\n  INNER JOIN publication p\r\n\tON p.id = pa.publication_id\r\n  INNER JOIN affiliation a\r\n\tON a.id = pa.affiliation_id\r\n\tINNER JOIN publication_subject ps\r\n\tON p.id = ps.publication_id\r\n\tINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\n  WHERE\r\n  (a.country = '$country' or '$country' = 'All') and ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n\t  and (a.city = '$city' or '$city' = 'All')\r\n\t    and (a.name = '$university' or '$university' = 'All')\r\n  GROUP BY date_trunc('year', p.cover_date::timestamp)\r\n  ORDER BY date_trunc('year', p.cover_date::timestamp)\r\n) s\r\nWHERE\r\n  $__timeFilter(s.year)"
    }
   ]
  },
  {
   "title": "Топ стран",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  current_date AS Time,\r\n  a.country AS Country,\r\n  count(*) AS Count\r\nFROM \r\n  publication_author pa\r\nINNER JOIN \r\n  publication p\r\n  ON p.id = pa.publication_id\r\nINNER JOIN \r\n  affiliation a\r\n\tON a.id = pa.affiliation_id\r\nINNER JOIN publication_subject ps\r\n\tON p.id = ps.publication_id\r\nINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\n  WHERE\r\n  ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n\t  and ('$year'= 'All' and date_part('year', p.cover_date::timestamp)::text <> '' or '$year' <> 'All' and date_part('year'::text, p.cover_date::timestamp)::text = '$year')\r\nGROUP BY \r\n  a.country\r\nORDER BY Count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Топ городов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  current_date AS Time,\r\n  a.city AS City,\r\n  count(*) AS Count\r\nFROM \r\n  publication_author pa\r\nINNER JOIN \r\n  publication p\r\n  ON p.id = pa.publication_id\r\nINNER JOIN \r\n  affiliation a\r\n\tON a.id = pa.affiliation_id\r\nINNER JOIN publication_subject ps\r\n\tON p.id = ps.publication_id\r\nINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\n  WHERE\r\n\t(a.country = '$country' or '$country' = 'All') and ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n\t  and ('$year'= 'All' and date_part('year', p.cover_date::timestamp)::text <> '' or '$year' <> 'All' and date_part('year'::text, p.cover_date::timestamp)::text = '$year')\r\n      and a.city IS NOT NULL\r\nGROUP BY \r\n  a.city\r\nORDER BY Count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Топ университетов",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  current_date AS Time,\r\n  a.name AS Univercity,\r\n  count(*) AS Count\r\nFROM \r\n  publication_author pa\r\nINNER JOIN \r\n  publication p\r\n  ON p.id = pa.publication_id\r\nINNER JOIN \r\n  affiliation a\r\n\tON a.id = pa.affiliation_id\r\nINNER JOIN publication_subject ps\r\n\tON p.id = ps.publication_id\r\nINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\nWHERE\r\n\t(a.country = '$country' or '$country' = 'All') and ('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n    and (a.city = '$city' or '$city' = 'All')\r\n      and ('$year'= 'All' and date_part('year', p.cover_date::timestamp)::text <> '' or '$year' <> 'All' and date_part('year'::text, p.cover_date::timestamp)::text = '$year')\r\nGROUP BY \r\n  a.name\r\nORDER BY Count DESC\r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Топ авторов Политех",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  au.name AS Author,\r\n  count(*) AS Count\r\nFROM \r\n  publication_author_2004 pa\r\nINNER JOIN \r\n  publication_2004 p\r\n  ON p.id = pa.publication_id\r\nINNER JOIN \r\n  author au\r\n  ON au.id = pa.author_id\r\nINNER JOIN \r\n  affiliation a\r\n\tON a.id = pa.affiliation_id\r\nINNER JOIN publication_subject_2004 ps\r\n\tON p.id = ps.publication_id\r\nINNER JOIN subject su\r\n\tON su.id = ps.subject_id\r\nWHERE\r\n\t('$subject' <> 'ALL' and su.short_name = '$subject' or '$subject' = 'ALL' and su.short_name <> '')\r\n    and \r\n    a.name like '%Peter the Great St. Petersburg Polytechnic University%'\r\n      --and ('$year'= 'All'or '$year' <> 'All' and date_part('year'::text, p.cover_date::timestamp)::text = '$year')\r\nGROUP BY \r\n  au.name\r\nORDER BY Count DESC\r\nLIMIT 10"
    }
   ]
  }
 ]
}